--- 
security: 
  basic: 
    enabled: false
  client: 
    accesTokenUri: "http://localhost:8001/auth/oath/token"
    clientId: ClientId
    clientSecret: secret
    userAuthorizationUri: "http://localhost:8001/auth/oath/authorize"
  oath2: ~
  resource: 
    userInfoUri: "http://localhost:8001/auth/rest/hello"
server: 
  context-path: /ui
  port: 8002
  session: 
    cookie: 
      name: UISESSION
spring: 
  thymeleaf: 
    cache: false
