server:
  port: 8002
  context-path: /ui
  session:
    cookie:
	  name: UISESSION
security:
  basic:
    enabled: false
  oath2:
  client:
    clientId: ClientId
    clientSecret: secret
    accesTokenUri: http://localhost:8001/auth/oath/token 
    userAuthorizationUri: http://localhost:8001/auth/oath/authorize
  resource:
    userInfoUri: http://localhost:8001/auth/rest/hello
			
spring:
  thymeleaf:
    cache: false 